USER_ID = '3xtuo6ymbt7h'
# Your PAT (Personal Access Token) can be found in the portal under Authentification
PAT = '8c4aa5d106d44c6e9da2ed8b1924b7f6'
APP_ID = 'text2text_testing'
WORKFLOW_ID = 'workflow-9f90b0'
WORKFLOW_ID_TEXT = 'workflow-9f90b0'
WORKFLOW_ID_IMAGE = 'workflow-9f90b0'
WORKFLOW_ID_STORY_GPT3 = 'workflow-9f90b0'