# Programming language file extensions and their corresponding names

[language_names]
asm = "Assembly"
c = "C"
cmake = "CMake"
coffee = "CoffeeScript"
cpp = "CPP"
cs = "CSharp"
csproj = "CSharp"
dart = "Dart"
fs = "FSharp"
fsi = "FSharp"
go = "Go"
groovy = "Groovy"
h = "C"
hpp = "CPP"
hs = "Haskell"
html = "HTML"
css = "CSS"
ipynb = "JupyterNotebook"
java = "Java"
jl = "Julia"
js = "JavaScript"
jsx = "JavaScript"
mjs = "JavaScript"
json = "JSON"
kt = "Kotlin"
lua = "Lua"
m = "ObjectiveC"
md = "Markdown"
mm = "CPP"
php = "PHP"
pl = "Perl"
ps1 = "PowerShell"
psm1 = "PowerShell"
py = "Python"
r = "R"
rb = "Ruby"
rs = "Rust"
rst = "reStructuredText"
s = "Assembly"
scala = "Scala"
sh = "Shell"
sql = "SQL"
pgsql = "PostgreSQL"
mssql = "SQL Server"
sqlite = "SQLite"
mysql = "MySQL"
svg = "SVG"
swift = "Swift"
swiftdeps = "Swift"
tex = "TeX"
toml = "TOML"
ts = "TypeScript"
tsx = "TypeScript"
txt = "Text"
v = "Verilog"
vh = "Verilog"
vue = "Vue.js"
xml = "XML"
yaml = "YAML"
yml = "YAML"
Makefile = "Makefile"
Dockerfile = "Dockerfile"
svelte = "Svelte"
wxs = "WiX"
scss = "Sassy CSS"
Pipfile = "Pipfile"
tf = "Terraform"
