[theme]
base="dark"
primaryColor="#bb9167"
backgroundColor="#f4e6db"
secondaryBackgroundColor="#c0b3ab"
textColor="#1a1513"
font="monospace"

[client]
toolbarMode="minimal"

[server]
maxUploadSize = 20