USER_ID = 'clarifai_user-id'
# Your PAT (Personal Access Token) can be found in the portal under Authentification
PAT = 'Clarifai_PAT'
APP_ID = 'Clarifai_APP_ID'
WORKFLOW_ID = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_TEXT = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_IMAGE = 'Clarifai_WORKFLOW_ID'
WORKFLOW_ID_STORY_GPT3 = 'Clarifai_WORKFLOW_ID'