langs = [
    ['Afrikaans', 'af'],
    ['Arabic', 'ar'],
    ['Belarusian', 'be'],
    ['Bulgarian', 'bg'],
    ['Bosnian', 'bs'],
    ['Simplified Chinese', 'zh-cn'],
    ['Traditional Chinese', 'zh-tw'],
    ['Chechen', 'che'],
    ['Czech', 'cs'],
    ['Danish', 'da'],
    ['German', 'de'],
    ['Spanish', 'es'],
    ['Estonian', 'et'],
    ['Persian', 'fa'],
    ['French', 'fr'],
    ['Irish', 'ga'],
    ['Hindi', 'hi'],
    ['Croatian', 'hr'],
    ['Hungarian', 'hu'],
    ['Indonesian', 'id'],
    ['Italian', 'it'],
    ['Japanese', 'ja'],
    ['Korean', 'ko'],
    ['Latin', 'la'],
    ['Lithuanian', 'lt'],
    ['Latvian', 'lv'],
    ['Mongolian', 'mn'],
    ['Malay', 'ms'],
    ['Maltese', 'mt'],
    ['Nepali', 'ne'],
    ['Dutch', 'nl'],
    ['Norwegian', 'no'],
    ['Polish', 'pl'],
    ['Portuguese', 'pt'],
    ['Romanian', 'ro'],
    ['Russian', 'ru'],
    ['Serbian', 'sr'],
    ['Slovak', 'sk'],
    ['Slovenian', 'sl'],
    ['Albanian', 'sq'],
    ['Swedish', 'sv'],
    ['Thai', 'th'],
    ['Turkish', 'tr'],
    ['Ukranian', 'uk'],
    ['Uzbek', 'uz'],
    ['Vietnamese', 'vi'],
]